// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-12-14 14:03:09

#import "MPDemoVipInfo.h"
#import "MPDemoUserInfo.h"

@implementation MPDemoUserInfo 


@end

