// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-12-14 14:03:09


@class MPDemoVipInfo;

@interface MPDemoVipInfo : NSObject

@property(nonatomic, assign) SInt64 expireTime;
@property(nonatomic, assign) SInt32 level;
@end

