// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-12-14 14:03:09


@class MPDemoVipInfo;
@class MPDemoUserInfo;

@interface MPDemoUserInfo : NSObject

@property(nonatomic, strong) NSString* name;
@property(nonatomic, assign) SInt32 age;
@property(nonatomic, strong) MPDemoVipInfo* vipInfo;
@end

