// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-12-14 14:03:09


@class MPDemoGetIdGetReq;

@interface MPDemoGetIdGetReq : NSObject

@property(nonatomic, strong) NSString* id;
@property(nonatomic, assign) SInt32 age;
@property(nonatomic, assign) BOOL isMale;
@end

