// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-12-14 14:03:09

@class MPDemoGetIdGetReq;
@class MPDemoUserInfo;
@class MPDemoPostPostReq;

@interface MPDemoRpcDemoClient : NSObject


-(MPDemoUserInfo *) getIdGet:(MPDemoGetIdGetReq *)requestParam;

-(MPDemoUserInfo *) postPost:(MPDemoPostPostReq *)requestParam;

-(NSString *) exceptionGet;

-(MPDemoUserInfo *) dataPostPb:(MPDemoPostPostReq *)requestParam;

-(MPDemoUserInfo *) dataPostLimit:(MPDemoPostPostReq *)requestParam;

-(MPDemoUserInfo *) dataPostNotExist:(MPDemoPostPostReq *)requestParam;

-(MPDemoUserInfo *) dataPostDecryptFailed:(MPDemoPostPostReq *)requestParam;

-(MPDemoUserInfo *) dataPostSetTimeout:(MPDemoPostPostReq *)requestParam;

-(MPDemoUserInfo *) dataPostAddHeader:(MPDemoPostPostReq *)requestParam;

@end
	
