// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2018-12-14 14:03:09

#import "MPDemoGetIdGetReq.h"
#import "MPDemoUserInfo.h"
#import "MPDemoPostPostReq.h"
#import "MPDemoRpcDemoClient.h"


@implementation MPDemoRpcDemoClient


-(MPDemoUserInfo *) getIdGet:(MPDemoGetIdGetReq *)requestParam{
	DTRpcMethod *method = [[DTRpcMethod alloc] init];
	method.operationType = @"com.antcloud.request.get";
	method.checkLogin =  NO ;
	method.signCheck =  YES ;
	method.returnType =   @"@\"MPDemoUserInfo\"";

	return [[DTRpcClient defaultClient] executeMethod:method params:@[ requestParam ? requestParam : [NSNull null]]];
}

/**************************************************************************/

-(MPDemoUserInfo *) postPost:(MPDemoPostPostReq *)requestParam{
	DTRpcMethod *method = [[DTRpcMethod alloc] init];
	method.operationType = @"com.antcloud.request.post";
	method.checkLogin =  NO ;
	method.signCheck =  YES ;
	method.returnType =   @"@\"MPDemoUserInfo\"";

	return [[DTRpcClient defaultClient] executeMethod:method params:@[ requestParam ? requestParam : [NSNull null]]];
}

/**************************************************************************/

-(NSString *) exceptionGet{
	DTRpcMethod *method = [[DTRpcMethod alloc] init];
	method.operationType = @"com.antcloud.request.exception";
	method.checkLogin =  NO ;
	method.signCheck =  YES ;
	method.returnType =   @"@\"NSString\"";

	return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}

/**************************************************************************/

-(MPDemoUserInfo *) dataPostPb:(MPDemoPostPostReq *)requestParam{
	DTRpcMethod *method = [[DTRpcMethod alloc] init];
	method.operationType = @"com.antcloud.request.postPb";
	method.checkLogin =  NO ;
	method.signCheck =  YES ;
	method.returnType =   @"@\"MPDemoUserInfo\"";

	return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}

/**************************************************************************/

-(MPDemoUserInfo *) dataPostLimit:(MPDemoPostPostReq *)requestParam
{
    DTRpcMethod *method = [[DTRpcMethod alloc] init];
    method.operationType = @"com.antcloud.request.postlimit";
    method.checkLogin =  NO ;
    method.signCheck =  YES ;
    method.returnType =   @"@\"MPDemoUserInfo\"";
    
    return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}

-(MPDemoUserInfo *) dataPostNotExist:(MPDemoPostPostReq *)requestParam
{
    DTRpcMethod *method = [[DTRpcMethod alloc] init];
    method.operationType = @"com.antcloud.request.postNotExist";
    method.checkLogin =  NO ;
    method.signCheck =  YES ;
    method.returnType =   @"@\"MPDemoUserInfo\"";
    
    return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}

// 服务端开加密了，客户端按接口关闭加密
-(MPDemoUserInfo *) dataPostDecryptFailed:(MPDemoPostPostReq *)requestParam
{
    DTRpcMethod *method = [[DTRpcMethod alloc] init];
    method.operationType = @"com.antcloud.request.post";
    method.checkLogin =  NO ;
    method.signCheck =  YES ;
    method.isCrypt = NO;    // 关闭加密
    method.returnType =   @"@\"MPDemoUserInfo\"";
    
    return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}

-(MPDemoUserInfo *) dataPostSetTimeout:(MPDemoPostPostReq *)requestParam
{
    DTRpcMethod *method = [[DTRpcMethod alloc] init];
    method.operationType = @"com.antcloud.request.post";
    method.checkLogin =  NO ;
    method.signCheck =  YES ;
    method.timeoutInterval = 1;     // 这个超时时间是客户端收到网关返回的时间，服务端配置的超时时间是后端业务系统的返回时间；默认 20s，设置小于 1 时无效即为默认值
    method.returnType =   @"@\"MPDemoUserInfo\"";
    
    return [[DTRpcClient defaultClient] executeMethod:method params:@[ ]];
}

-(MPDemoUserInfo *) dataPostAddHeader:(MPDemoPostPostReq *)requestParam
{
    DTRpcMethod *method = [[DTRpcMethod alloc] init];
    method.operationType = @"com.antcloud.request.postAddHeader";
    method.checkLogin =  NO ;
    method.signCheck =  YES ;
    method.returnType =   @"@\"MPDemoUserInfo\"";
    
    // 针对接口添加 header
    NSDictionary *customHeader = @{@"testKey": @"testValue"};
    return [[DTRpcClient defaultClient] executeMethod:method params:@[ ] requestHeaderField:customHeader responseHeaderFields:nil];
}

@end
	
	
